version: '3'
services:
  hq:
    environment: 
      HQ_Headquarters__BaseUrl: https://${HQ_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hq.rule=Host(`${HQ_HOST}`)"
      - "traefik.http.routers.hq.entrypoints=websecure"
      - "traefik.http.routers.hq.tls.certresolver=le"
      - "traefik.http.services.hq.loadbalancer.passhostheader=true"

  traefik:
    image: "traefik:v2.3"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${LETS_ENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    volumes:
    - "letsencrypt:/letsencrypt"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    ports:
      - "443:443"
      - "80:80"
volumes:  
  letsencrypt: